#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test?replicaSet=demo

#spring:
#  data:
#    mongodb:
#      uri: mongodb://mongo-node1:27017,mongo-node2:27018,mongo-node3:27019/test?replicaSet=demo

#spring:
#  data:
#    mongodb:
#      uri: mongodb://mongo-node1:27017/test?replicaSet=demo

# With authentication
#spring:
#  data:
#    mongodb:
#      uri: mongodb://john:johnpass@localhost:27017,localhost:27018,localhost:27019/test?replicaSet=demo


# Check quick setup

spring:
  data:
    mongodb:
      host: localhost
      database: partner-service-db
      username: user
      password: Welcome1_
